anchors_education = [
    "Fetch the official transcript for a specific student ID.",
    "Update a student's emergency contact and family relationship details.",
    "Verify a student's enrollment status for the current academic term.",
    "Update a student's preferred name in the active directory.",
    "Export attendance records for a specific course date range.",
    "Retrieve a student's medical allergy alerts for the school nurse.",
    "Update the permanent mailing address for a student's household.",
    "Request a list of active students currently in the 10th-grade cohort.",
    "Flag a senior student's record for graduation clearance review.",
    "Log a student's daily attendance or absence record.",
    "Create a new syllabus module for the upcoming semester's course.",
    "Publish the midterm examination schedule to the main course page.",
    "Create a new class section with a maximum student enrollment limit..",
    "Unpublish a deprecated reading assignment module from student view.",
    "Copy curriculum materials from last semester's course to the current active shell.",
    "Add a Teaching Assistant to the course roster with grading and editing permissions.",
    "Archive a completed past-semester course from the active faculty dashboard.",
    "Update the course description and prerequisite requirements in the academic catalog.",
    "Create a new assignment drop-box with a specified cutoff date and time.",
    "Reorder the visibility sequence of course modules in the student portal.",
    "Enter a numeric grade for a student's submitted assignment.",
    "Update the grading rubric criteria for the final capstone project.",
    "Calculate the weighted final GPA for a student at the end of the term.",
    "Set a student's assignment submission status to excused.",
    "Exempt a student from a specific quiz grade due to an excused medical absence.",
    "Apply a 10% late penalty deduction to a tardy assignment submission.",
    "Bulk upload student midterm grades from a CSV file into the LMS gradebook.",
    "Release finalized semester grades to the student viewing portal.",
    'Modify the weight of the "Participation" grading category to 15% of the final grade.',
    "Add qualitative, text-based feedback comments to a student's essay submission.",
    "Post a class-wide announcement regarding a sudden lecture room change.",
    "Return a graded coursework submission back to the student.",
    "Send an invitation to a parent or guardian to link their email to a student's profile.",
    "Open a new discussion board thread for this week's assigned readings.",
    "Reply directly to a student's question in the course Q&A forum.",
    "Retrieve the list of student submissions for a specific coursework assignment.",
    "Remove a published announcement from the course stream.",
    "Schedule an automated welcome announcement to publish on Monday morning at 8 AM.",
    "Broadcast an emergency campus weather closure alert to all faculty and students.",
    "Extend or modify the due date for an existing course assignment.",
    "Create a new course category to organize related courses.",
    "Add a scheduled event to the digital course calendar.",
    "Create a new digital project group within a course.",
    "Manually grant a user access to a specific digital course.",
    "Assign a specific permission role to a user within a course context.",
    "Suspend a user's enrollment in a specific course.",
    "Upload a file to a user's private file area.",
    "Cancel and remove a scheduled event from the digital course calendar.",
    "Duplicate an existing digital learning activity or resource module.",
    "Import digital resources and activities from a previous course into a new one.",
]

anchors_finance = [
    "Retrieve the current available balance for a specific checking account using the real-time balance endpoint.",
    "Fetch the routing and account numbers for an institutional bank connection.",
    "Retrieve the historical list of transactions for a specific credit account.",
    "Verify the identity information associated with a connected bank account.",
    "Disconnect a specific financial institution from the user's profile.",
    "Retrieve the real-time authorization status of a connected financial account.",
    "Filter a specific account's transaction history by a designated date range.",
    "Retrieve the overarching asset summary for a connected user profile.",
    "Query the current available credit limit on a connected credit card.",
    "Fetch the categorized breakdown of expenses for a specific bank account.",
    "Create a new payment authorization for a specified fiat amount.",
    "Capture the funds for a previously authorized payment intent.",
    "Issue a full refund for a completed payment transaction back to the customer.",
    "Cancel a pending payment authorization before the funds are captured.",
    "Update the shipping address metadata on an active payment intent.",
    "Confirm a payment intent to trigger the customer authentication flow.",
    "Issue a partial refund for a specific amount on a completed transaction.",
    "Retrieve the success or failure status of a specific payment attempt.",
    "Create a Checkout Session with a specified discount coupon.",
    "Capture a PaymentIntent for a specified amount less than or equal to its authorized amount.",
    "Submit a market order to purchase shares of a specific equity.",
    "Submit a limit order to sell an asset at a designated target price.",
    "Retrieve the current open positions in the active investment portfolio.",
    "Cancel a pending, unexecuted stock order.",
    "Retrieve the current market value and unrealized profit/loss for all open positions.",
    "Liquidate all open positions to convert the portfolio entirely to cash.",
    "Replace an active order to adjust the requested share quantity.",
    "Fetch the current buying power and cash balance of the trading account.",
    "Query the real-time market price quote for a specific ticker symbol.",
    "Transfer a specified cash amount from the trading account to a linked bank account.",
    "Create a new draft invoice for a designated customer profile.",
    "Add a specific line item charge to an existing draft invoice.",
    "Finalize a draft invoice to prepare it for external payment routing.",
    "Void an issued invoice that was generated in error.",
    "Delete a draft invoice before it is finalized.",
    "Mark a finalized invoice as uncollectible to close the billing cycle.",
    "Send a finalized invoice to a customer via an automated email notification.",
    "Apply a customer credit balance to reduce the total amount of an invoice.",
    "Retrieve a list of all past-due invoices for a specific client account.",
    "Update the default payment due date on an existing draft invoice.",
    "Create a new virtual corporate card assigned to a specific cardholder.",
    "Update the monthly spending limit on an active corporate card.",
    "Freeze a corporate card to temporarily decline all new authorizations.",
    "Cancel a corporate card to permanently deactivate it.",
    "Update the approved merchant category codes for a specific corporate card.",
    "Retrieve the list of pending authorizations for a specific cardholder.",
    "Approve an incoming card authorization when it satisfies the card's configured spending controls.",
    "Decline an incoming card authorization that violates the card's configured spending controls.",
    "Update the billing address associated with a specific cardholder profile.",
    "Retrieve the physical shipping status of a newly minted corporate card.",
]

anchors_legal = [
    "Create a new draft envelope containing a standard non-disclosure agreement.",
    "Add a new recipient to an existing signature routing order.",
    "Void an active envelope to cancel the pending signature request.",
    "Retrieve the current signature status of a specific contract envelope.",
    "Download the completed, signed PDF document from an envelope.",
    "Add a required signature tab to a specific coordinate on a document page.",
    "Update the email address of a pending recipient in an active envelope.",
    "Resend the signature notification email to a pending recipient.",
    "Delete one or more documents from a draft envelope.",
    "Append an addendum document to an existing draft envelope.",
    "Create a new legal matter assigned to a specific client profile.",
    "Update the status of an active legal matter to closed.",
    "Add a new billable time entry to a specific legal matter.",
    "Generate a new draft invoice for unbilled time on a matter.",
    "Add a new contact profile for a prospective legal client.",
    "Update the primary billing address for an existing client contact.",
    "Upload a digital evidence file to a specific matter's document folder.",
    "Retrieve the current available balance in a client's trust account.",
    "Delete a draft, unbilled time entry from the daily log.",
    "Assign a specific responsible attorney to a legal matter.",
    "Search for a Philippine Supreme Court decision using a specific G.R. number.",
    "Retrieve the full text of a specific Republic Act or statutory code.",
    "Filter a search query for jurisprudence by a specific date range.",
    "Extract the list of cited legal authorities from a specific court decision.",
    "Save a specific case document to a custom legal research folder.",
    "Create an automated search alert for a specific legal keyword or entity.",
    "Retrieve the official metadata and syllabus for a specific statute.",
    "Fetch the algorithmic list of related cases for a given Supreme Court decision.",
    "Download a PDF version of an original court ruling document.",
    "Retrieve the subsequent citing history to check if a case has been overturned.",
    "Search for a registered Philippine corporate entity by its SEC registration number.",
    "Retrieve the documented list of active directors and corporate officers.",
    "Fetch the chronological filing history of a specific corporate entity.",
    "Filter corporate entities by their official date of incorporation.",
    "Retrieve the current registered principal address of a company.",
    "Retrieve the list of registered subsidiary companies for a parent entity.",
    "Check the current active or inactive legal status of a corporate entity.",
    "Fetch the standardized industry classification code for a specific company.",
    "Retrieve the registered trademark data associated with a corporate entity.",
    "Search for corporate entities matching a specific phonetic name pattern.",
    "Retrieve active public bidding notices issued by a specific government agency.",
    "Fetch the official Notice of Award for a completed government procurement.",
    "Filter public bidding opportunities by the Approved Budget for the Contract (ABC).",
    "Search for public government contracts using specific industry keywords.",
    "Download the attached technical specifications document for a bidding notice.",
    "Retrieve the listed project location details for an infrastructure procurement.",
    "Fetch the official procurement mode classification for a specific contract.",
    "Retrieve the scheduled date and time for a procurement pre-bid conference.",
    "Fetch the corporate registry details of the winning bidder for a contract.",
    "Retrieve the chronological timeline of updates for a specific bidding notice.",
]

anchors_insurance = [
    "Retrieve the detailed coverage and term information for an active policy.",
    "Initiate a formal cancellation request for an active insurance policy.",
    "Initiate a renewal transaction for an expiring insurance policy.",
    "Update the mailing address for the primary named insured on a policy.",
    "Retrieve the list of properties or locations covered under a specific policy.",
    "Start a policy change transaction to modify existing coverage details.",
    "Reinstate a previously canceled insurance policy to active status.",
    "Retrieve the list of specific coverages and limits applied to a policy.",
    "Download or retrieve official documents attached to an active policy.",
    "Add a new additional insured to a policy change transaction.",
    "File a new First Notice of Loss (FNOL) to create a new claim record.",
    "Retrieve the status and details of an existing insurance claim.",
    "Assign an open claim to a specific claims adjuster or group.",
    "Add an internal diary note or update to a specific claim file.",
    "Close a completed claim after all exposures have been resolved.",
    "Retrieve the list of specific incident exposures attached to a claim.",
    "Close an open claim exposure after resolving the associated loss.",
    "Upload a digital evidence document to a claim file.",
    "Add a new involved party or witness contact to a claim record.",
    "Update the financial reserve amount allocated for a specific claim exposure.",
    "Retrieve the current financial summary for a premium billing account.",
    "Process a new incoming premium payment against a billing account.",
    "Retrieve the list of generated invoices for a specific billing account.",
    "Change the recurring payment plan schedule for a billing account.",
    "Retrieve the chronological history of payments made on an account.",
    "Add a new payment instrument to a billing profile.",
    "Create a disbursement from a billing account to return a premium overpayment.",
    "Apply a received payment directly to a specific outstanding invoice.",
    "Write off an unpaid invoice balance as uncollectible bad debt.",
    "Update the billing or mailing address associated with a premium account.",
    "Retrieve a patient's Medicare and supplemental coverage information.",
    "Fetch a specific Explanation of Benefit record for a medical claim.",
    "Retrieve the demographic profile of the insured patient beneficiary.",
    "Search for all Explanation of Benefit records tied to a specific patient.",
    "Retrieve patient coverage information using a specific beneficiary identifier.",
    "Fetch the Patient resource for the authenticated beneficiary.",
    "Retrieve a specific Coverage resource for the authenticated beneficiary.",
    "Retrieve a patient's Explanation of Benefit records updated within a specified time interval.",
    "Filter a patient's Explanation of Benefit records by claim type.",
    "Retrieve the available Explanation of Benefit records for the authenticated beneficiary.",
    "Create a new insurance policy submission to begin the quoting process.",
    "Generate a premium quote for a pending insurance submission.",
    "Bind the coverage and issue a pending submission into an active policy.",
    "Formally decline an insurance submission due to unacceptable underwriting risk.",
    "Withdraw a pending submission from consideration at the applicant's request.",
    "Retrieve the detailed status and data of an active policy submission.",
    "Add a new property location to an ongoing commercial policy submission.",
    "Add an additional insured to a pending submission job.",
    "Update risk assessment questionnaire answers on a pending submission.",
    "Retrieve the current status and underwriting information for a pending submission job.",
]

anchors_hr = [
    "Retrieve the demographic profile data and contact details for a specific employee.",
    "Update the primary residential address for a specific employee's profile.",
    "Fetch the current employment status and official job title for a user.",
    "Add a new emergency contact record to an employee's profile.",
    "Upload a digital document to a specific employee's secure personnel file.",
    "Retrieve employee records associated with a specific manager.",
    "Update the employee's name fields used in the company directory.",
    "Terminate an employee's profile by updating their active employment status.",
    "Add a new dependent to an employee's digital benefits profile.",
    "Retrieve employee records from a saved custom report containing directory fields.",
    "Create a new candidate profile in the applicant tracking system.",
    "Advance a candidate's application to the next designated interview stage.",
    "Reject a candidate's application and apply a specific rejection reason code.",
    "Add a new internal note to a candidate's activity feed.",
    "Retrieve the completed interview scorecard submitted for a specific candidate.",
    "Upload a resume file attachment to an existing candidate profile.",
    "Create a new open job requisition in the applicant tracking system.",
    "Update the hiring team assignment for a specific open job.",
    "Retrieve scheduled interviews associated with a specific application or candidate.",
    "Add a tracking tag to a candidate's profile.",
    "Retrieve the current compensation and wage details for a specific employee.",
    "Add a one-time bonus compensation item for a specific employee.",
    "Update the hourly wage rate for a non-exempt employee profile.",
    "Retrieve the detailed pay stub for a specific historical payroll run.",
    "Add a pre-tax deduction to an employee's recurring payroll profile.",
    "Update the federal tax withholding parameters for a specific employee.",
    "Retrieve the calculated totals and deductions for a specific processed payroll.",
    "Update an employee's employment status/end date in the payroll system.",
    "Fetch the bank account routing details used for an employee's direct deposit.",
    "Add a reimbursable expense for a specific employee.",
    "Log a new completed time entry for a specific workspace.",
    "Stop the currently active time tracker for a user.",
    "Delete an erroneous time entry from the workspace.",
    "Change an existing time entry to be marked as billable.",
    "Retrieve a list of time entries logged by a specific user.",
    "Create a new project within a workspace to track time against.",
    "Add a new categorical tag to the workspace for organizing time entries.",
    "Retrieve the list of all workspaces the authenticated user has access to.",
    "Create a new client profile to associate with time-tracked projects.",
    "Update the default hourly billing rate for a specific project.",
    "Retrieve the list of active performance goals for a specific employee.",
    "Update the status of a specific employee goal to completed.",
    "Create a new performance goal for a specific employee.",
    "Delete an erroneous or duplicate goal from an employee's profile.",
    "Retrieve the list of all open onboarding and general tasks for the authenticated user.",
    "Mark a specific assigned task as complete.",
    "Retrieve the organizational and employment data for a specific employee profile.",
    "Retrieve employee records for a specified set of employees.",
    "Search the employee directory using specific filtering criteria.",
    "Retrieve the employment lifecycle history for a specific employee.",
]

anchors_customer_service = [
    "Create a new support ticket for a reported customer issue.",
    "Update the priority level of an existing open support ticket.",
    "Add an internal note to a specific support ticket for team reference.",
    "Assign a support ticket to a specific agent or team queue.",
    "Retrieve the full conversation history for a specific ticket.",
    "Change the status of a support ticket to pending customer response.",
    "Merge two duplicate support tickets into a single unified record.",
    "Add a public reply comment to a ticket visible to the customer.",
    "Delete a spam or test ticket from the active support queue.",
    "Retrieve all open tickets assigned to a specific agent.",
    "Update the email address associated with a customer account.",
    "Retrieve the complete profile information for a specific customer.",
    "Change the phone number on file for a customer account.",
    "Add a new secondary contact to an existing business account.",
    "Deactivate a customer account that is no longer active.",
    "Retrieve the account creation date and status for a customer.",
    "Update the preferred communication channel for a customer.",
    "Merge two duplicate customer accounts into one profile.",
    "Add a billing address to a customer account record.",
    "Retrieve the list of all accounts associated with a specific organization.",
    "Initiate a live chat session with an available support agent.",
    "Send a scripted greeting message to a customer in queue.",
    "Retrieve the current chat transcript for an active session.",
    "Transfer an active chat session to a specialized support queue.",
    "End a live chat session after successful issue resolution.",
    "Send a file attachment to a customer via the chat interface.",
    "Update the chat agent's availability status to offline.",
    "Retrieve the estimated wait time for customers in the chat queue.",
    "Escalate a chat session to a human supervisor.",
    "Send a satisfaction survey request at the end of a chat session.",
    "Search the knowledge base for articles matching a customer query.",
    "Retrieve the full text of a specific help article by ID.",
    "Create a new draft knowledge article for a resolved issue.",
    "Publish a draft article to the customer-facing self-service portal.",
    "Update the keywords and search tags for an existing article.",
    "Retrieve the list of most-viewed articles in a category.",
    "Archive a deprecated knowledge article from public view.",
    "Link a support ticket to a relevant knowledge article.",
    "Retrieve the version history for a specific knowledge article.",
    "Suggest related articles based on a customer's open ticket.",
    "Escalate an unresolved ticket to the tier-2 support team.",
    "Route a billing inquiry to the specialized finance support queue.",
    "Transfer a technical issue to the engineering escalation path.",
    "Assign a high-priority ticket to the on-call supervisor.",
    "Retrieve the escalation history for a specific customer account.",
    "Update the disposition code for a resolved support interaction.",
    "Reopen a closed ticket that requires additional investigation.",
    "Route a compliance-related inquiry to the legal review team.",
    "Retrieve the list of pending escalations for a specific team.",
    "Update the escalation reason code for a support case.",
]

anchors_federal = [
    "Retrieve the veteran's medical records from the VA health system.",
    "Verify the applicant's service-connected disability rating.",
    "Calculate the monthly benefit amount based on disability percentage.",
    "Generate the formal eligibility determination letter.",
    "Check the remaining entitlement for GI Bill education benefits.",
    "Verify Medicare Part A eligibility based on work history.",
    "Calculate the student loan forgiveness amount under PSLF.",
    "Retrieve the applicant's immigration visa petition status.",
    "Verify disaster assistance eligibility based on declared area.",
    "Process a Social Security retirement application for a citizen.",
    "File a federal tax return for a citizen using electronic filing.",
    "Check the status of a pending tax refund.",
    "Retrieve the taxpayer's wage and income transcript.",
    "Submit a payment for owed federal taxes.",
    "Verify the identity of a taxpayer before account access.",
    "Update the direct deposit information for a tax refund.",
    "Apply an Individual Protection PIN to a taxpayer account.",
    "Retrieve the list of tax documents filed by third parties.",
    "Calculate the estimated tax liability based on reported income.",
    "Submit an extension request for filing a federal tax return.",
    "Submit a FOIA request for agency records on a specific topic.",
    "Retrieve the status of a pending FOIA request.",
    "Verify the identity of a FOIA requester.",
    "Search for publicly available records before processing a FOIA request.",
    "Send an acknowledgment of receipt to a FOIA requester.",
    "Apply privacy exemptions to redact personal information from released records.",
    "Forward a FOIA request to the appropriate agency office.",
    "Calculate the processing fee for a large FOIA request.",
    "Send a denial letter citing specific FOIA exemptions.",
    "File an appeal for a denied FOIA request.",
    "Retrieve active public bidding notices issued by a specific agency.",
    "Fetch the official Notice of Award for a completed procurement.",
    "Filter bidding opportunities by the Approved Budget for the Contract.",
    "Search for government contracts using specific industry keywords.",
    "Download the technical specifications for a bidding notice.",
    "Retrieve the project location details for an infrastructure procurement.",
    "Fetch the procurement mode classification for a specific contract.",
    "Retrieve the scheduled date for a pre-bid conference.",
    "Fetch the corporate registry details of the winning bidder.",
    "Retrieve the chronological timeline of updates for a bidding notice.",
    "File a workplace safety complaint with OSHA for a specific hazard.",
    "Submit a Request for Assistance under the SENA program.",
    "Verify the identity of a worker filing a safety complaint.",
    "Retrieve the status of a pending workplace safety inspection.",
    "Forward a labor dispute case to the appropriate regional office.",
    "Schedule a conciliation-mediation session for a labor dispute.",
    "Retrieve the list of pending complaints for a specific employer.",
    "Submit an anonymous safety complaint through the online form.",
    "Verify the employer's compliance history with OSHA standards.",
    "Send a notice of inspection to the employer's registered address.",
]

anchors_health = [
    "Update the residential address and primary contact telephone number for an existing outpatient.",
    "Record the official date and verified time of death on a deceased inpatient's medical record.",
    "Register a designated legal guardian as the primary emergency contact for a pediatric patient.",
    "Log the patient's preferred spoken language and interpreter requirement in their demographic profile.",
    "Assign an in-network primary care physician as the designated general practitioner for an enrolled patient.",
    "Mark a duplicate patient chart as inactive and link its identifier forward to the authoritative master record.",
    "Establish a cross-facility reference link between two regional clinic profiles belonging to the same individual.",
    "Link a newborn's clinical chart to the mother's inpatient maternity encounter profile.",
    "Perform a Master Patient Index probabilistic query to match incoming intake demographics against existing hospital charts.",
    "Query the patient administration registry using legal surname and date of birth to confirm active enrollment status.",
    "Book a confirmed outpatient consultation in an open provider slot for a referred patient.",
    "Reschedule an existing specialty consultation to a later available calendar slot.",
    "Cancel a scheduled clinic visit upon patient request and document the cancellation reason code.",
    "Dispatch an internal patient transport task requesting wheelchair assistance to diagnostic radiology.",
    "Mark an assigned specimen collection task as completed and record the collection timestamp.",
    "Record a clinical task non-fulfillment exception due to patient unavailability and update the task status reason.",
    "Admit a patient to an inpatient surgical ward and assign an initial room and bed location.",
    "Finalize an inpatient encounter status to completed and document the discharge disposition to home care.",
    "Add an attending consulting physician to the active encounter participant roster.",
    "Retrieve the chronological location history and movement track of a completed patient encounter.",
    "Retrieve the most recent resting blood pressure and pulse rate observations recorded for an outpatient.",
    "Query the laboratory observation registry for fasting blood glucose and HbA1c values recorded over the past six months.",
    "Inspect newly posted serum potassium laboratory observations flagged with an abnormal or critical interpretation code.",
    "Record an encounter vital sign observation panel documenting systolic pressure, diastolic pressure, and body temperature.",
    "Correct a typographical entry error on a preliminary vital sign observation and document the amendment reason.",
    "Access the final validated DiagnosticReport and associated atomic observations for a routine Complete Blood Count panel.",
    "Retrieve the radiologist's formal diagnostic conclusion and narrative report for a completed outpatient chest X-ray.",
    "Check the completion status and preliminary findings of a surgical biopsy pathology report.",
    "Assign an attending pathologist as the primary results interpreter responsible for final report sign-off.",
    "Append a clinical addendum note to a finalized diagnostic report without overwriting previous diagnostic conclusions.",
    "Issue an electronic outpatient prescription for an acute 10-day oral antibiotic course.",
    "Authorize a 90-day maintenance prescription refill for an established hypertension medication.",
    "Update a maintenance insulin prescription with titrated daily dosage instructions while referencing the prior prescription.",
    "Discontinue an active anticoagulant prescription order and document the adverse reaction reason code.",
    "Place an active oral hypoglycemic medication order on temporary hold prior to an elective surgical procedure.",
    "Authorize generic bioequivalent substitution for a branded cholesterol medication request.",
    "Designate a patient-selected retail community pharmacy as the fulfillment dispenser for an active electronic prescription.",
    "Log a patient-reported over-the-counter daily aspirin regimen into the medical record for informational reconciliation.",
    "Order an urgent intravenous electrolyte replacement dose for an admitted inpatient under the active hospital encounter.",
    "Link a documented chronic condition diagnosis and supporting lab result to a restricted formulary medication request.",
    "Verify that a patient's primary commercial health insurance policy is active and in-force for the scheduled date of service.",
    "Retrieve the applicable specialist consultation co-pay and annual deductible limit from the patient's active coverage plan.",
    "Set the coordination-of-benefits priority order designating a group employer plan as primary and a supplemental plan as secondary.",
    "Register a self-pay financial arrangement designating an uninsured patient as solely responsible for outpatient treatment costs.",
    "Submit an electronic prior-authorization request to an insurer for a proposed outpatient surgical procedure.",
    "Submit a predetermination claim to explore estimated insurer coverage and out-of-pocket patient liability for restorative dental work.",
    "Submit an electronic professional healthcare claim for reimbursement covering completed physical therapy sessions.",
    "Attach required clinical narrative justification and a secondary diagnostic code to a pending electronic claim.",
    "Void an active electronic claim submitted with an incorrect billing modifier code and mark its status as cancelled.",
    "Submit a retail pharmacy reimbursement claim linking the approved prior authorization reference number and provider prescription.",
]

anchors_all = [
    anchors_education,
    anchors_finance,
    anchors_legal,
    anchors_insurance,
    anchors_hr,
    anchors_customer_service,
    anchors_federal,
    anchors_health,
]
